[package]
name = "hid-user"
version = "0.1.3"
edition = "2021"
links = "X11,Xtst"
license = "GPL-3.0"

[dependencies]
bitfield = "0.14"
env_logger = "0.11"
log = "0.4"
rusb = { version = "0.9", features = ["vendored"] }
usbsas-sandbox = { path = "../../usbsas-sandbox" }
x11 = "2.21"
